Repository Real-Dev-Squad/website-members, pull requests merged in 2020-12, with the labels that each got.

#79 Fetching and displaying PRs on individual member page
  components/member-profile/index.js
  helper-functions/fetch.js
  helper-functions/getPRs.js
  package-lock.json
  package.json
Labels: enhancement, feature-task

#81 Changed API endpoint for fetching pull requests
  helper-functions/getPRs.js
Labels: bug-fix

#89 Basic badges setup for members
  components/member-profile/index.js
  components/member-profile/member-profile.module.scss
  components/member-profile/mock/data.json
  components/member-profile/mock/get-badges.js
  public/images/badge.jpeg
Labels: feature-task
