Repository Real-Dev-Squad/website-members, pull requests merged in 2021-02, with the labels that each got.

#116 Adds CI using Github Actions
  .github/workflows/continuous-integration.yml
Labels: feature-task

#120 Eslint side-drawer error fixed
  components/UI/side-drawer/index.js
Labels: bug-fix

#114 Click event added to member card
  components/member-list-item/index.js
Labels: enhancement

#119 Updating CONTRIBUTING.md to adapt to git flow
  CONTRIBUTING.md
Labels: documentation
